services:
  dmml:
    build: .
    container_name: dmml-recsys
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      - caddy_network
    restart: unless-stopped

networks:
  caddy_network:
    external: true
